ARG version
FROM almalinux:${version:-8}
ARG COURSE = "DEVOPS"
ARG TRAINER = "sandeep"
ARG DURATION = "100HRS"
RUN echo "Course is: ${COURSE}, Trainer is: ${TRAINER}, Duration is: ${Duration}"
CMD["sleep","200"]